on:
  push:
    branches: master

name: npm-publish

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: npm ci
      - run: npm test
      - uses: JS-DevTools/npm-publish@v3
        id: publish
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
      - if: ${{ steps.publish.outputs.type }}
        name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION="v${{ steps.publish.outputs.version }}"
          gh release create $VERSION --generate-notes
